### ISSUE TITLE
Should also be in Kinc-Samples

### ISSUE THREAD

**Issue by RobDangerous** [luboslenco/kinc_3dexamples#1]
Please allow Rob to also copy them to https://github.com/Kode/Kinc-Samples and run automatic checks on them. Technically the license allows it of course but I wanted to ask anyway. The GitHub-Actions in that repository run automatically for each Kinc-commit, I'm in the process of also making them run for consoles and I also want to add reference-screenshot-comparison-tests like with the Shader-test in the Kinc-repo.

**Comment by luboslenco** [comment]
Will be more than happy if you get to use them.

>  I also want to add reference-screenshot-comparison-tests

Amazing! Just need to add `kinc_g4_render_targets_inverted_y` handling in some examples.
